version: '3.3'

services:
  db:
    image: "mysql:latest"
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql:/var/lib/mysql"
    restart: always

    environment:
      - MYSQL_ROOT_PASSWORD=secret123
      - MYSQL_DATABASE=esisfo
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
      

  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db